package api_workspace.enums;

public enum CollaborationEventType {

    COLLECTION_CREATED,
    COLLECTION_UPDATED,
    COLLECTION_DELETED,

    REQUEST_CREATED,
    REQUEST_UPDATED,
    REQUEST_DELETED,
    REQUEST_MOVED,

    ENVIRONMENT_CREATED,
    ENVIRONMENT_UPDATED,
    ENVIRONMENT_DELETED,

    VARIABLE_CREATED,
    VARIABLE_UPDATED,
    VARIABLE_DELETED
}