spring.application.name=api-workspace
spring.datasource.url=jdbc:postgresql://localhost:5432/api_workspace
spring.datasource.username=postgres
spring.datasource.password=changeme

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
jwt.secret=f6ea1b717081baa2808dcec72478797aaac9c417bfea05453d1336b2f7462fcf
